version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  api-gateway:
    build: ./apps/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  auth-service:
    build: ./apps/auth
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  market-service:
    build: ./apps/market-data
    ports:
      - "3003:3003"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend-admin
    ports:
      - "3002:3000"