
version: '3.8'

services:
  # üê∞ RabbitMQ: ‡∏ï‡∏±‡∏ß‡∏Å‡∏•‡∏≤‡∏á‡∏™‡πà‡∏á‡∏Ç‡πâ‡∏≠‡∏Ñ‡∏ß‡∏≤‡∏°
  rabbitmq:
    image: rabbitmq:3-management
    container_name: algo_rabbitmq
    ports:
      - "5672:5672"   # Port ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö Code ‡πÄ‡∏ä‡∏∑‡πà‡∏≠‡∏°‡∏ï‡πà‡∏≠
      - "15672:15672" # Port ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö‡∏´‡∏ô‡πâ‡∏≤‡πÄ‡∏ß‡πá‡∏ö‡∏à‡∏±‡∏î‡∏Å‡∏≤‡∏£
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - algo-net

  # üçÉ MongoDB: ‡∏ê‡∏≤‡∏ô‡∏Ç‡πâ‡∏≠‡∏°‡∏π‡∏•
  mongo:
    image: mongo
    container_name: algo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - algo-net

networks:
  algo-net:

volumes:
  mongo_data: